security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Define tu proveedor de usuarios personalizado
        app_user_provider:
            id: App\Security\CustomEntityUserProvider

    firewalls:
        login:
            pattern: ^/api/usuario/login
            stateless: true
            json_login:
                check_path: /api/usuario/login
                username_path: correo
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api/capitulos
            stateless: true
            #  jwt: true

        # Desactiva la seguridad para el entorno de desarrollo
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Configura el firewall principal
        # main:
        #     lazy: true
        #     provider: app_user_provider

    access_control:
        - { path: ^/api/usuario/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/usuario/registro, roles: PUBLIC_ACCESS }
        - { path: ^/api/capitulos, roles: PUBLIC_ACCESS }
