controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

about:
    path: /about
    controller: App\Controller\AboutController::getAboutText

contact:
    path: /contact
    controller: App\Controller\ContactController::getContactText

obra_show:
    path: /obra/{titulo}
    controller: App\Controller\ObraController::getSpecificObra

app_get_obra_by_id:
    path: /api/obra/{id}
    controller: App\Controller\ObraController::getObraById
    methods: GET

crear_comentario:
    path: /api/comentarios
    controller: App\Controller\ComentarioController::crearComentario
    methods: POST
