controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

about:
    path: /about
    controller: App\Controller\AboutController::getAboutText

contact:
    path: /contact
    controller: App\Controller\ContactController::getContactText


obra_show:
    path: /obra/{titulo}
    controller: App\Controller\ObraController::getSpecificObra
