# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
 
# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Define tus parámetros si los necesitas
 
services:
    # Configuración predeterminada para los servicios en *este* archivo
    _defaults:
        autowire: true       # Inyecta automáticamente las dependencias en tus servicios.
        autoconfigure: true  # Registra automáticamente tus servicios como comandos, suscriptores de eventos, etc.
 
    # Permite que las clases en src/ estén disponibles para ser usadas como servicios
    # Esto crea un servicio por clase cuyo ID es el nombre de clase completamente cualificado
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
 
    # Agrega definiciones de servicios adicionales cuando se necesite configuración explícita
    # Por favor, ten en cuenta que las últimas definiciones siempre *reemplazan* a las anteriores
 
    # Controlador de éxito de autenticación personalizado
    app.service.customAuthService:
        class: App\Service\CustomAuthService
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.handler.authentication_success, method: handleSuccessfulAuthentication }